---
title: "Non_attri_analyse_2"
author: "Yifan Du"
date: "12/5/2021"
output: pdf_document
---

```{r}
noun_1 <- c('class')
noun_2 <- c('trainer', 'instructor', 'teacher', 'coach', 'staff')
noun_3 <- c('manager', 'employee', 'service')
noun_4 <- c('equipment', 'machine', 'space', 'treadmill')
noun_5 <- c('shower', 'towel', 'water', 'bathroom')
noun_6 <- c('locker', 'facility', 'parking') 
noun_7 <- c('workout', 'fitness')
noun_8 <- c('money', 'fee')
```


```{r}
review_gym_noun_1_senti = read.csv('review_gym_noun_1_senti.csv')
review_gym_noun_1_senti = review_gym_noun_1_senti[,-1]

review_gym_noun_2_senti = read.csv('review_gym_noun_2_senti.csv')
review_gym_noun_2_senti = review_gym_noun_2_senti[,-1]

review_gym_noun_3_senti = read.csv('review_gym_noun_3_senti.csv')
review_gym_noun_3_senti = review_gym_noun_3_senti[,-1]

review_gym_noun_4_senti = read.csv('review_gym_noun_4_senti.csv')
review_gym_noun_4_senti = review_gym_noun_4_senti[,-1]

review_gym_noun_5_senti = read.csv('review_gym_noun_5_senti.csv')
review_gym_noun_5_senti = review_gym_noun_5_senti[,-1]

review_gym_noun_6_senti = read.csv('review_gym_noun_6_senti.csv')
review_gym_noun_6_senti = review_gym_noun_6_senti[,-1]

review_gym_noun_8_senti = read.csv('review_gym_noun_8_senti.csv')
review_gym_noun_8_senti = review_gym_noun_8_senti[,-1]

```



```{r}
noun_1_star_positive = review_gym_noun_1_senti$stars[which(review_gym_noun_1_senti$sentiment == 1)]
noun_1_star_neutral = review_gym_noun_1_senti$stars[which(review_gym_noun_1_senti$sentiment == 0)]
noun_1_star_negative = review_gym_noun_1_senti$stars[which(review_gym_noun_1_senti$sentiment == -1)]

t.test(noun_1_star_positive, noun_1_star_neutral, alternative = "two.sided", var.equal = FALSE)

t.test(noun_1_star_neutral, noun_1_star_negative, alternative = "two.sided", var.equal = FALSE)

t.test(noun_1_star_positive, noun_1_star_negative, alternative = "two.sided", var.equal = FALSE)

# barplot(c(mean(noun_2_star_positive), mean(noun_2_star_neutral), mean(noun_2_star_negative)))

```



```{r}
noun_2_star_positive = review_gym_noun_2_senti$stars[which(review_gym_noun_2_senti$sentiment == 1)]
noun_2_star_neutral = review_gym_noun_2_senti$stars[which(review_gym_noun_2_senti$sentiment == 0)]
noun_2_star_negative = review_gym_noun_2_senti$stars[which(review_gym_noun_2_senti$sentiment == -1)]

t.test(noun_2_star_positive, noun_2_star_neutral, alternative = "two.sided", var.equal = FALSE)

t.test(noun_2_star_neutral, noun_2_star_negative, alternative = "two.sided", var.equal = FALSE)

t.test(noun_2_star_positive, noun_2_star_negative, alternative = "two.sided", var.equal = FALSE)

# barplot(c(mean(noun_2_star_positive), mean(noun_2_star_neutral), mean(noun_2_star_negative)))

```

```{r}
noun_3_star_positive = review_gym_noun_3_senti$stars[which(review_gym_noun_3_senti$sentiment == 1)]
noun_3_star_neutral = review_gym_noun_3_senti$stars[which(review_gym_noun_3_senti$sentiment == 0)]
noun_3_star_negative = review_gym_noun_3_senti$stars[which(review_gym_noun_3_senti$sentiment == -1)]

t.test(noun_3_star_positive, noun_3_star_neutral, alternative = "two.sided", var.equal = FALSE)

t.test(noun_3_star_neutral, noun_3_star_negative, alternative = "two.sided", var.equal = FALSE)

t.test(noun_3_star_positive, noun_3_star_negative, alternative = "two.sided", var.equal = FALSE)
```


```{r}
noun_4_star_positive = review_gym_noun_4_senti$stars[which(review_gym_noun_4_senti$sentiment == 1)]
noun_4_star_neutral = review_gym_noun_4_senti$stars[which(review_gym_noun_4_senti$sentiment == 0)]
noun_4_star_negative = review_gym_noun_4_senti$stars[which(review_gym_noun_4_senti$sentiment == -1)]

t.test(noun_4_star_positive, noun_4_star_neutral, alternative = "two.sided", var.equal = FALSE)

t.test(noun_4_star_neutral, noun_4_star_negative, alternative = "two.sided", var.equal = FALSE)

t.test(noun_4_star_positive, noun_4_star_negative, alternative = "two.sided", var.equal = FALSE)

```


```{r}
noun_5_star_positive = review_gym_noun_5_senti$stars[which(review_gym_noun_5_senti$sentiment == 1)]
noun_5_star_neutral = review_gym_noun_5_senti$stars[which(review_gym_noun_5_senti$sentiment == 0)]
noun_5_star_negative = review_gym_noun_5_senti$stars[which(review_gym_noun_5_senti$sentiment == -1)]

t.test(noun_5_star_positive, noun_5_star_neutral, alternative = "two.sided", var.equal = FALSE)

t.test(noun_5_star_neutral, noun_5_star_negative, alternative = "two.sided", var.equal = FALSE)

t.test(noun_5_star_positive, noun_5_star_negative, alternative = "two.sided", var.equal = FALSE)

```

```{r}
noun_6_star_positive = review_gym_noun_6_senti$stars[which(review_gym_noun_6_senti$sentiment == 1)]
noun_6_star_neutral = review_gym_noun_6_senti$stars[which(review_gym_noun_6_senti$sentiment == 0)]
noun_6_star_negative = review_gym_noun_6_senti$stars[which(review_gym_noun_6_senti$sentiment == -1)]

t.test(noun_6_star_positive, noun_6_star_neutral, alternative = "two.sided", var.equal = FALSE)

t.test(noun_6_star_neutral, noun_6_star_negative, alternative = "two.sided", var.equal = FALSE)

t.test(noun_6_star_positive, noun_6_star_negative, alternative = "two.sided", var.equal = FALSE)

```

```{r}
noun_8_star_positive = review_gym_noun_8_senti$stars[which(review_gym_noun_8_senti$sentiment == 1)]
noun_8_star_neutral = review_gym_noun_8_senti$stars[which(review_gym_noun_8_senti$sentiment == 0)]
noun_8_star_negative = review_gym_noun_8_senti$stars[which(review_gym_noun_8_senti$sentiment == -1)]

t.test(noun_8_star_positive, noun_8_star_neutral, alternative = "two.sided", var.equal = FALSE)

t.test(noun_8_star_neutral, noun_8_star_negative, alternative = "two.sided", var.equal = FALSE)

t.test(noun_8_star_positive, noun_8_star_negative, alternative = "two.sided", var.equal = FALSE)

```





